services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"
    labels:
      caddy.enable: true
      caddy.host: "solemnity.icu"
      caddy.tls: "prod"
